apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: phpadmin-pod
  name: phpadmin-pod
spec:
  containers:
  - image: phpmyadmin
    name: phpadmin-pod
    envFrom:
    - configMapRef:
        name: phpadmin-config
    - secretRef:
        name: phpadmin-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: phpadmin-svc
spec:
  selector:
    run: phpadmin-pod
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 80
  type: NodePort  # Expose externally using NodePort (or LoadBalancer if needed)
